### ISSUE TITLE
Doc url has changed

### ISSUE THREAD

**Issue by softlion** [jfversluis/Microsoft-Docs-Langyfier#1]
Hey, could you update the extension so it works with the new doc url ? ty !

**Comment by jfversluis** [comment]
Oh that's a good one! I might do that. I think the "problem" is that I then also need to make more updates to make it compatible with all the latest things... 😅 I'll have a look, glad to see people are actually still using this!

**Comment by jfversluis** [comment]
I've submitted a new version to the Chrome Extension Store which should hopefully be released soon and will work with the updated domain name.

Thanks!

**Comment by softlion** [comment]
ty it's online ! And yes I use this extension everyday. Nice work. Shame to ms.

**Comment by jfversluis** [comment]
Awesome! Had to do some rewriting since the APIs changed. Let me know if you see anything weird.
